<SideLabel@MDLabel>:
	theme_text_color:'Primary'
	font_size:27
	font_name: 'Product Sans Regular.ttf'

<ClockButton@MDFillRoundFlatIconButton>:
	icon:'clock'
	text : 'Set'
	width:dp(100)
<ShowTimeLabel@MDLabel>:
	theme_text_color: 'Primary'
    font_name: 'Product Sans Regular.ttf'	

<DefaultLabel@MDLabel>:
    theme_text_color: 'Primary'
    halign: 'center'
    font_name: 'Product Sans Regular.ttf'

<DefaultInput@MDTextField>:
    size_hint:(0.50, 0.10)
